---
include:
  # ----- Build resets ------
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nicenano_reset

  - board: lpgalaxy_blank_slate
    shield: settings_reset
    artifact-name: blankslate_reset


  # - board: nice_nano_v2
  #   shield: dactyls_left
  # - board: nice_nano_v2
  #   shield: dactyls_right

  # - board: nice_nano_v2
  #   shield: rev41_oled

  # - board: nice_nano_v2
  #   shield: putiti60

  # - board: nice_nano_v2
  #   shield: putiti36_choc

  # - board: nice_nano_v2
  #   shield: putiti36_oled
  
  # - board: nice_nano_v2
  #   shield: choc-corne_left
  # - board: nice_nano_v2
  #   shield: choc-corne_right

  # - board: nice_nano_v2
  #   shield: putiti40_kb
  # - board: nice_nano_v2
  #   shield: putiti40_dongle

  # - board: nice_nano_v2
  #   shield: rev41_oled

  # ----- Blank Slate Keyboard W/out Dongle ------
  # - board: lpgalaxy_blank_slate

  # ----- Dactyl Split Keyboard ------
  # - board: nice_nano_v2
  #   shield: dactyl_left
  # - board: nice_nano_v2
  #   shield: dactyl_right
  # - board: nice_nano_v2

  # ----- Dactyl Display Dongle Keyboard ------
  #   shield: dactyl_dongle dongle_display
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  # ----- Blank Slate Dongle ------
  # - board: nice_nano_v2
  #   shield: blank-slate_dongle dongle_display
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  # ----- Putiti48_choc ------
  - board: nice_nano_v2
    shield: putiti48_choc
