---
include:
  - board: nice_nano_v2
    shield: settings_reset

  # - board: nice_nano_v2
  #   shield: dactyls_left
  # - board: nice_nano_v2
  #   shield: dactyls_right

  # - board: nice_nano_v2
  #   shield: rev41_oled

  # - board: nice_nano_v2
  #   shield: putiti60

  # - board: nice_nano_v2
  #   shield: putiti36_choc

  # - board: nice_nano_v2
  #   shield: putiti36_oled
  
  # - board: nice_nano_v2
  #   shield: choc-corne_left
  # - board: nice_nano_v2
  #   shield: choc-corne_right

  # - board: nice_nano_v2
  #   shield: putiti40_kb
  # - board: nice_nano_v2
  #   shield: putiti40_dongle

 # - board: nice_nano_v2
 # shield: dactyl_left
 # - board: nice_nano_v2
 # shield: dactyl_right
 # - board: nice_nano_v2
 # shield: dactyl_dongle



  - board: lpgalaxy_blank_slate
    # snippet: studio-rpc-usb-uart
    shield: blank_slate_kb
  - board: nice_nano_v2
    shield: blank_slate_dongle
  - board: lpgalaxy_blank_slate
    shield: settings_reset

    
