---
include:
  # ----- Build resets ------
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nicenano_reset

  - board: lpgalaxy_blank_slate
    shield: settings_reset
    artifact-name: blankslate_reset
  # -------------------------


  # --- Dactyl Split Keyboard ----
  # - board: nice_nano_v2
  #   shield: dactyls_left
  # - board: nice_nano_v2
  #   shield: dactyls_right
  # ------------------------------


  # ----- Reviung41 OLED -------
  - board: nice_nano_v2
    shield: rev41_oled
  # ----------------------------


  # -------- Putiti60 ----------
  # - board: nice_nano_v2
  #   shield: putiti60
  # ----------------------------
  

  # ------ Putiti36_choc -------
  # - board: nice_nano_v2
  #   shield: putiti36_choc
  # ----------------------------


  # ------ Putiti36 OLED -------
  # - board: nice_nano_v2
  #   shield: putiti36_oled
  # ----------------------------
  

  # ----- Choc-corne ------
  # - board: nice_nano_v2
  #   shield: choc-corne_left
  # - board: nice_nano_v2
  #   shield: choc-corne_right
  # -----------------------


  # ------- Putiti40 --------
  # - board: nice_nano_v2
  #   shield: putiti40_kb
  # - board: nice_nano_v2
  #   shield: putiti40_dongle
  # -------------------------


  # ----- Blank Slate Keyboard W/out Dongle ------
  # - board: lpgalaxy_blank_slate
  # ----------------------------------------------


  # ----- Dactyl Split W/Dongle Keyboard ------
  # - board: nice_nano_v2
  #   shield: dactyl_left
  # - board: nice_nano_v2
  #   shield: dactyl_right
  # - board: nice_nano_v2
  #   shield: dactyl_dongle dongle_display
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  # ----------------------------------


  # ----- Blank Slate Dongle ------
  # - board: nice_nano_v2
  #   shield: blank-slate_dongle dongle_display
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  # -------------------------------


  # ----- Putiti48_choc ------
  - board: nice_nano_v2
    shield: putiti48_choc
  # --------------------------
